name: README Update Automation

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    name: Update README after PR merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js using the latest stable version
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Extract PR Number and Commit SHA from the GitHub event context
      - name: Get PR Info
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      # Run the JavaScript script
      - name: Generate Updated README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_PATH: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: node main.js

      # Additional step to enable debugging, helps in troubleshooting
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
